# Generated by Django 4.2.1 on 2023-09-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productUrl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
